# Permalinks
permalink:           pretty

# Setup
title:               Wired Dude
tagline:             specify imports for directory _sass
url:                 http://dmkanter.github.io
paginate:            1
baseurl:             ""

# Assets
#
# We specify the directory for Jekyll so we can use @imports.
sass:
  sass_dir:          _sass
  style:            :compressed

# About/contact
author:
  name:              David Kanter
  url:               https://twitter.com/dmkanter
  email:             figureitout@gmaill.com 

# Custom vars
version:             2.0.0
github:
  repo:              https://github.com/dmkanter/dmkanter.github.io

# Gems
gems:
  - jekyll-paginate
  - jekyll-gist
