# Site settings
title: dmkanter.github.io
email: david@davidkanter.com
description: > # this means to ignore newlines until "baseurl:"
  Someday, will Write an awesome description of my site here. For now, you just get to read my various online tests and experiments.
baseurl: "" # the subpath of your site, e.g. /blog/
url: "http://dmkanter.github.io" # the base hostname & protocol for your site
twitter_username: dmkanter
github_username: dmkanter

# Build settings
markdown: kramdown
